### ISSUE TITLE
Failed to execute phase [query] all shard

### ISSUE THREAD

**Issue by smokingwheels** [loklak/loklak_server#10]
After Startup does not happen again.
Not sure if hardware fault but peer is restarted with searches being asked of it during startup.

2015-04-17 03:41:52.533:WARN::qtp403370592-42: Failed to execute phase [query], all shards failed; shardFailures {[Rm52FeIGSlSSmooer2pPYw][messages][0]: SearchParseException[[messages][0]: query[+text:twitter],from[0],size[100]: Parse Failure [Failed to parse source [{"from":0,"size":100,"query":{"bool":{"must":{"match":{"text":{"query":"twitter","type":"boolean"}}}}},"sort":[{"created_at":{"order":"desc"}}]}]]]; nested: SearchParseException[[messages][0]: query[+text:twitter],from[0],size[100]: Parse Failure [No mapping found for [created_at] in order to sort on]]; }{[Rm52FeIGSlSSmooer2pPYw][messages][1]: SearchParseException[[messages][1]: query[+text:twitter],from[0],size[100]: Parse Failure [Failed to parse source [{"from":0,"size":100,"query":{"bool":{"must":{"match":{"text":{"query":"twitter","type":"boolean"}}}}},"sort":[{"created_at":{"order":"desc"}}]}]]]; nested: SearchParseException[[messages][1]: query[+text:twitter],from[0],size[100]: Parse Failure [No mapping found for [created_at] in order to sort on]]; }{[Rm52FeIGSlSSmooer2pPYw][messages][2]: SearchParseException[[messages][2]: query[+text:twitter],from[0],size[100]: Parse Failure [Failed to parse source [{"from":0,"size":100,"query":{"bool":{"must":{"match":{"text":{"query":"twitter","type":"boolean"}}}}},"sort":[{"created_at":{"order":"desc"}}]}]]]; nested: SearchParseException[[messages][2]: query[+text:twitter],from[0],size[100]: Parse Failure [No mapping found for [created_at] in order to sort on]]; }{[Rm52FeIGSlSSmooer2pPYw][messages][3]: SearchParseException[[messages][3]: query[+text:twitter],from[0],size[100]: Parse Failure [Failed to parse source [{"from":0,"size":100,"query":{"bool":{"must":{"match":{"text":{"query":"twitter","type":"boolean"}}}}},"sort":[{"created_at":{"order":"desc"}}]}]]]; nested: SearchParseException[[messages][3]: query[+text:twitter],from[0],size[100]: Parse Failure [No mapping found for [created_at] in order to sort on]]; }{[Rm52FeIGSlSSmooer2pPYw][messages][4]: SearchParseException[[messages][4]: query[+text:twitter],from[0],size[100]: Parse Failure [Failed to parse source [{"from":0,"size":100,"query":{"bool":{"must":{"match":{"text":{"query":"twitter","type":"boolean"}}}}},"sort":[{"created_at":{"order":"desc"}}]}]]]; nested: SearchParseException[[messages][4]: query[+text:twitter],from[0],size[100]: Parse Failure [No mapping found for [created_at] in order to sort on]]; }{[Rm52FeIGSlSSmooer2pPYw][messages][5]: SearchParseException[[messages][5]: query[+text:twitter],from[0],size[100]: Parse Failure [Failed to parse source [{"from":0,"size":100,"query":{"bool":{"must":{"match":{"text":{"query":"twitter","type":"boolean"}}}}},"sort":[{"created_at":{"order":"desc"}}]}]]]; nested: SearchParseException[[messages][5]: query[+text:twitter],from[0],size[100]: Parse Failure [No mapping found for [created_at] in order to sort on]]; }{[Rm52FeIGSlSSmooer2pPYw][messages][6]: SearchParseException[[messages][6]: query[+text:twitter],from[0],size[100]: Parse Failure [Failed to parse source [{"from":0,"size":100,"query":{"bool":{"must":{"match":{"text":{"query":"twitter","type":"boolean"}}}}},"sort":[{"created_at":{"order":"desc"}}]}]]]; nested: SearchParseException[[messages][6]: query[+text:twitter],from[0],size[100]: Parse Failure [No mapping found for [created_at] in order to sort on]]; }{[Rm52FeIGSlSSmooer2pPYw][messages][7]: SearchParseException[[messages][7]: query[+text:twitter],from[0],size[100]: Parse Failure [Failed to parse source [{"from":0,"size":100,"query":{"bool":{"must":{"match":{"text":{"query":"twitter","type":"boolean"}}}}},"sort":[{"created_at":{"order":"desc"}}]}]]]; nested: SearchParseException[[messages][7]: query[+text:twitter],from[0],size[100]: Parse Failure [No mapping found for [created_at] in order to sort on]]; }
org.elasticsearch.action.search.SearchPhaseExecutionException: Failed to execute phase [query], all shards failed; shardFailures {[Rm52FeIGSlSSmooer2pPYw][messages][0]: SearchParseException[[messages][0]: query[+text:twitter],from[0],size[100]: Parse Failure [Failed to parse source [{"from":0,"size":100,"query":{"bool":{"must":{"match":{"text":{"query":"twitter","type":"boolean"}}}}},"sort":[{"created_at":{"order":"desc"}}]}]]]; nested: SearchParseException[[messages][0]: query[+text:twitter],from[0],size[100]: Parse Failure [No mapping found for [created_at] in order to sort on]]; }{[Rm52FeIGSlSSmooer2pPYw][messages][1]: SearchParseException[[messages][1]: query[+text:twitter],from[0],size[100]: Parse Failure [Failed to parse source [{"from":0,"size":100,"query":{"bool":{"must":{"match":{"text":{"query":"twitter","type":"boolean"}}}}},"sort":[{"created_at":{"order":"desc"}}]}]]]; nested: SearchParseException[[messages][1]: query[+text:twitter],from[0],size[100]: Parse Failure [No mapping found for [created_at] in order to sort on]]; }{[Rm52FeIGSlSSmooer2pPYw][messages][2]: SearchParseException[[messages][2]: query[+text:twitter],from[0],size[100]: Parse Failure [Failed to parse source [{"from":0,"size":100,"query":{"bool":{"must":{"match":{"text":{"query":"twitter","type":"boolean"}}}}},"sort":[{"created_at":{"order":"desc"}}]}]]]; nested: SearchParseException[[messages][2]: query[+text:twitter],from[0],size[100]: Parse Failure [No mapping found for [created_at] in order to sort on]]; }{[Rm52FeIGSlSSmooer2pPYw][messages][3]: SearchParseException[[messages][3]: query[+text:twitter],from[0],size[100]: Parse Failure [Failed to parse source [{"from":0,"size":100,"query":{"bool":{"must":{"match":{"text":{"query":"twitter","type":"boolean"}}}}},"sort":[{"created_at":{"order":"desc"}}]}]]]; nested: SearchParseException[[messages][3]: query[+text:twitter],from[0],size[100]: Parse Failure [No mapping found for [created_at] in order to sort on]]; }{[Rm52FeIGSlSSmooer2pPYw][messages][4]: SearchParseException[[messages][4]: query[+text:twitter],from[0],size[100]: Parse Failure [Failed to parse source [{"from":0,"size":100,"query":{"bool":{"must":{"match":{"text":{"query":"twitter","type":"boolean"}}}}},"sort":[{"created_at":{"order":"desc"}}]}]]]; nested: SearchParseException[[messages][4]: query[+text:twitter],from[0],size[100]: Parse Failure [No mapping found for [created_at] in order to sort on]]; }{[Rm52FeIGSlSSmooer2pPYw][messages][5]: SearchParseException[[messages][5]: query[+text:twitter],from[0],size[100]: Parse Failure [Failed to parse source [{"from":0,"size":100,"query":{"bool":{"must":{"match":{"text":{"query":"twitter","type":"boolean"}}}}},"sort":[{"created_at":{"order":"desc"}}]}]]]; nested: SearchParseException[[messages][5]: query[+text:twitter],from[0],size[100]: Parse Failure [No mapping found for [created_at] in order to sort on]]; }{[Rm52FeIGSlSSmooer2pPYw][messages][6]: SearchParseException[[messages][6]: query[+text:twitter],from[0],size[100]: Parse Failure [Failed to parse source [{"from":0,"size":100,"query":{"bool":{"must":{"match":{"text":{"query":"twitter","type":"boolean"}}}}},"sort":[{"created_at":{"order":"desc"}}]}]]]; nested: SearchParseException[[messages][6]: query[+text:twitter],from[0],size[100]: Parse Failure [No mapping found for [created_at] in order to sort on]]; }{[Rm52FeIGSlSSmooer2pPYw][messages][7]: SearchParseException[[messages][7]: query[+text:twitter],from[0],size[100]: Parse Failure [Failed to parse source [{"from":0,"size":100,"query":{"bool":{"must":{"match":{"text":{"query":"twitter","type":"boolean"}}}}},"sort":[{"created_at":{"order":"desc"}}]}]]]; nested: SearchParseException[[messages][7]: query[+text:twitter],from[0],size[100]: Parse Failure [No mapping found for [created_at] in order to sort on]]; }
	at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.onFirstPhaseResult(TransportSearchTypeAction.java:238)
	at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction$1.onFailure(TransportSearchTypeAction.java:184)
	at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:565)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Orbiter** [comment]
The message "Parse Failure [No mapping found for [created_at] in order to sort on]" is typical for a situation where the elasticsearch index is not yet set up. I experienced this as well but don't know a way yet to check wether the elasticsearch index is ready or not.

Solution: just wait some seconds (about 10) until submitting the first search

**Comment by smokingwheels** [comment]
Has not happened on the last two upgrades.
