### ISSUE TITLE
Automatic updates fail on windows because of execution of shell scripts

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_server#1046]
```
java.io.IOException: Cannot run program "C:\Users\t-sus\Downloads\loklak_server-1.0-pre\bin\upgrade.sh": CreateProcess error=193, %1 is not a valid Win32 application
```

Looks like the caretaker process fails upgrade because it's trying to run a shell script instead of a file execution format that windows understands.

**Comment by yukiisbored** [comment]
Is there a full stack trace? It doesn't show which class causes the problem

**Comment by sudheesh001** [comment]
```
2017-03-03 09:06:24.134:INFO :DAO:CARETAKER: UPGRADE: starting an upgrade
2017-03-03 09:06:24.145:WARN :Caretaker:CARETAKER: UPGRADE failed: Cannot run program "C:\Users\t-sus\Downloads\loklak_server-1.0-pre\bin\upgrade.sh": CreateProcess error=193, %1 is not a valid Win32 application
java.io.IOException: Cannot run program "C:\Users\t-sus\Downloads\loklak_server-1.0-pre\bin\upgrade.sh": CreateProcess error=193, %1 is not a valid Win32 application
        at java.lang.ProcessBuilder.start(Unknown Source) ~[?:1.8.0_121]
        at java.lang.Runtime.exec(Unknown Source) ~[?:1.8.0_121]
        at java.lang.Runtime.exec(Unknown Source) ~[?:1.8.0_121]
        at java.lang.Runtime.exec(Unknown Source) ~[?:1.8.0_121]
        at org.loklak.tools.OS.execSynchronous(OS.java:250) ~[loklak_server-all.jar:?]
        at org.loklak.Caretaker.upgrade(Caretaker.java:239) [loklak_server-all.jar:?]
        at org.loklak.Caretaker.run(Caretaker.java:91) [loklak_server-all.jar:?]
Caused by: java.io.IOException: CreateProcess error=193, %1 is not a valid Win32 application
        at java.lang.ProcessImpl.create(Native Method) ~[?:1.8.0_121]
        at java.lang.ProcessImpl.<init>(Unknown Source) ~[?:1.8.0_121]
        at java.lang.ProcessImpl.start(Unknown Source) ~[?:1.8.0_121]
        ... 7 more
2017-03-03 09:06:24.147:INFO :DAO:CARETAKER: UPGRADE: started an upgrade
```
