### ISSUE TITLE
java.lang.IndexOutOfBoundsException: No group 7

### ISSUE THREAD

**Issue by smokingwheels** [loklak/loklak_server#11]
Working fine. 
Peer has been under light load for a day.

2015-04-17 14:36:42.500:INFO::qtp403370592-42: /api/search.json?q=ArianaGrande&timezoneOffset=-480&maximumRecords=100&source=twitter&minified=true
java.lang.IndexOutOfBoundsException: No group 7
	at java.util.regex.Matcher.start(Matcher.java:374)
	at java.util.regex.Matcher.appendReplacement(Matcher.java:831)
	at java.util.regex.Matcher.replaceFirst(Matcher.java:955)
	at org.loklak.scraper.TwitterScraper$TwitterTweet.<init>(TwitterScraper.java:282)
	at org.loklak.scraper.TwitterScraper.search(TwitterScraper.java:165)
	at org.loklak.scraper.TwitterScraper.search(TwitterScraper.java:70)
	at org.loklak.DAO.scrapeTwitter(DAO.java:625)
	at org.loklak.api.server.SearchServlet.doGet(SearchServlet.java:107)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:364)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:309)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:313)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:626)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:546)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Orbiter** [comment]
code changed a lot and cannot be found there at at org.loklak.scraper.TwitterScraper$TwitterTweet.(TwitterScraper.java:282) any more. Please check if this appears again.
