### ISSUE TITLE
Link unshortener fails to shorten several URLs

### ISSUE THREAD

**Issue by singhpratyush** [loklak/loklak_server#1114]
- Issue type: Bug report

### Short description

Loklak fails to unshorten many URLs, most of them are of type `https://fb.me/*`.

### Environment

 - Operating system: CentOS 7
 - Software version: Even with `loklak:development`.
 - Software source: Github Repository

### Steps to reproduce

1. Run loklak
```bash
$ ./bin/start.sh
```
2. Look at the log
```bash
$ tail -f data/loklak.log | less
```
3. You can see that unshorten fails for many URLs.

### Expected behaviour
The links should be shortened.

### Actual behaviour
Shortening links fail.

**Comment by singhpratyush** [comment]
From what I can see, the unshortening fails because of two major reasong - 

### 1. Redirects with non 301 status code
Most of the fail logs are coming because of [this](https://github.com/loklak/loklak_server/commit/9b4a7585bc893b064aaf4ac79119ca1c842fd269) -
```java
            if (httpResponse.getStatusLine().getStatusCode() == 301) {
                for (Header header: httpResponse.getAllHeaders()) {
                    if (header.getName().toLowerCase().equals("location")) return header.getValue();
                }
                throw new IOException("redirect for  " + urlstring+ ": no location attribute found");
            } else {
                throw new IOException("no redirect for  " + urlstring+ " fail: " + httpResponse.getStatusLine().getStatusCode() + ": " + httpResponse.getStatusLine().getReasonPhrase());
            }
```
 It throws an exception when status code is not 301.

Though the implementation is correct, it gives a false alarm for the logger. It can simply return the original URL in the case and it will do fine.

The URLs which do not give 301 but need redirection lead to webpages which set `http-equiv="refresh"` meta tag to redirect. e.g. -
```html
$ curl http://okt.to/CV08b4
<!DOCTYPE HTML>
<html>
<head>
...
	<meta http-equiv="refresh" content="2;url=https://www.marketingweek.com/2017/04/19/does-digital-culture-exist/">
...
</head>
<body>
...
</body>
</html>
```
In such cases, we can get the unshortened URL from the HTML content of the response.

@Orbiter: Shall I try to fetch the URL from HTML in case of 2XX status code?

### 2. `SSLHandshakeException`
I noticed this type of stack trace while I was connected to my college's network - 
```java
javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1002) ~[?:1.8.0_131]
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385) ~[?:1.8.0_131]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413) ~[?:1.8.0_131]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397) ~[?:1.8.0_131]
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394) ~[loklak_server-all.jar:?]
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353) ~[loklak_server-all.jar:?]
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141) ~[loklak_server-all.jar:?]
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353) ~[loklak_server-all.jar:?]
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380) ~[loklak_server-all.jar:?]
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[loklak_server-all.jar:?]
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[loklak_server-all.jar:?]
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) ~[loklak_server-all.jar:?]
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[loklak_server-all.jar:?]
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[loklak_server-all.jar:?]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[loklak_server-all.jar:?]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107) ~[loklak_server-all.jar:?]
        at org.loklak.http.ClientConnection.getRedirect(ClientConnection.java:261) ~[loklak_server-all.jar:?]
        at org.loklak.http.ClientConnection.getRedirect(ClientConnection.java:291) ~[loklak_server-all.jar:?]
        at org.loklak.harvester.RedirectUnshortener.unShorten(RedirectUnshortener.java:81) [loklak_server-all.jar:?]
        at org.loklak.harvester.TwitterScraper.unshorten(TwitterScraper.java:559) [loklak_server-all.jar:?]
        at org.loklak.harvester.TwitterScraper$TwitterTweet.run(TwitterScraper.java:489) [loklak_server-all.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.io.EOFException: SSL peer shut down incorrectly
        at sun.security.ssl.InputRecord.read(InputRecord.java:505) ~[?:1.8.0_131]
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983) ~[?:1.8.0_131]
        ... 23 more
```
I think that these are due to Cyberoam and firewall things. These may be resolved by using proper proxy settings.
```java
System.setProperty("http.proxyHost", "proxy.com");
System.setProperty("http.proxyPort", "911");
```
