### ISSUE TITLE
YoutubeScraper fails with NumberFormatException

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_server#1143]
After merge of https://github.com/loklak/loklak_server/pull/1106/ the YoutubeScraper fails:

```
java.lang.NumberFormatException: For input string: "4,8Mio."
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.parseLong(Long.java:631)
	at org.loklak.harvester.YoutubeScraper.parseNumber(YoutubeScraper.java:210)
	at org.loklak.harvester.YoutubeScraper.parseVideo(YoutubeScraper.java:137)
	at org.loklak.harvester.YoutubeScraperTest.whneTryParseVideoFromBufferedReaderShouldCheckThatIsGoodJsonObjectReturn(YoutubeScraperTest.java:40)
```

**Comment by vrnsky** [comment]
@Orbiter could you provide URL on which test failed
