### ISSUE TITLE
NullPointerException in CareTaker.java

### ISSUE THREAD

**Issue by vibhcool** [loklak/loklak_server#1191]
### Issue type: Bug report

This exception appears occasionally

### Traceback from loklak.log
```
2017-05-26 00:40:45.004:WARN :org.loklak.data.DAO:CARETAKER: CARETAKER THREAD
java.lang.NullPointerException
	at org.loklak.data.ElasticsearchClient.readMap(ElasticsearchClient.java:500) ~[loklak_server-all.jar:?]
	at org.loklak.data.AbstractIndexFactory.readJSON(AbstractIndexFactory.java:139) ~[loklak_server-all.jar:?]
	at org.loklak.data.AbstractIndexFactory.read(AbstractIndexFactory.java:91) ~[loklak_server-all.jar:?]
	at org.loklak.data.DAO.scrapeTwitter(DAO.java:1153) ~[loklak_server-all.jar:?]
	at org.loklak.data.DAO.scrapeTwitter(DAO.java:1111) [loklak_server-all.jar:?]
	at org.loklak.Caretaker.run(Caretaker.java:192) [loklak_server-all.jar:?]
```

**Comment by vibhcool** [comment]
working on this!
