### ISSUE TITLE
Server fails to start  could not create JVM

### ISSUE THREAD

**Issue by smokingwheels** [loklak/loklak_server#122]
Worked fine 8 hours ago was doing some harvesting and changed the backend peer setting on my frontend peer and starting is failing.
My Vserver has 768 meg of ram total and about 160 m allocated after reboot.
The front peers have approx 70000 MSG.
I have tried making Xmx bigger but still ont start.

Invalid maximum heap size: -Xmx256m
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

Error when shutting down
2015-09-03 08:28:42.800:INFO:oejsh.ContextHandler:Thread-7: Stopped o.e.j.s.ServletContextHandler@1d915082{/,null,UNAVAILABLE}
2015-09-03 08:28:43.941:WARN::qtp1489239019-50: 
org.eclipse.jetty.io.EofException
	at org.eclipse.jetty.server.HttpConnection$SendCallback.reset(HttpConnection.java:610)
	at org.eclipse.jetty.server.HttpConnection$SendCallback.access$100(HttpConnection.java:582)
	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:464)
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:766)
	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:804)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:142)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:135)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:378)
	at java.io.OutputStream.write(OutputStream.java:75)
	at org.eclipse.jetty.server.HttpOutput.print(HttpOutput.java:516)
	at org.loklak.api.server.SearchServlet.doGet(SearchServlet.java:209)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:364)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:309)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:313)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:626)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:546)
	at java.lang.Thread.run(Thread.java:745)
2015-09-03 08:28:43.944:INFO::main: server terminated
2015-09-03 08:28:43.945:INFO::Thread-18: catched caretaker termination signal
2015-09-03 08:28:43.945:INFO::Thread-18: closing DAO
2015-09-03 08:28:43.946:INFO::Thread-17: caretaker terminated
2015-09-03 08:28:45.463:INFO::Thread-18: closed DAO
2015-09-03 08:28:45.468:INFO::Thread-18: main terminated, goodby.
Invalid maximum heap size: -Xmx256m
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by Orbiter** [comment]
There is no fix for this problem because it is caused either by insufficient memory in your machine or bad parameter in the Xmx configuration.
