### ISSUE TITLE
RedirectUnshortener test fails

### ISSUE THREAD

**Issue by singhpratyush** [loklak/loklak_server#1261]
- Issue type: Bug report

### Short description
```java
org.loklak.harvester.RedirectUnshortenerTest > testRedirectUnshortener FAILED
    org.junit.ComparisonFailure: expected:<http[]://www.mostviralfeed...> but was:<http[s]://www.mostviralfeed...>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at org.loklak.harvester.RedirectUnshortenerTest.testRedirectUnshortener(RedirectUnshortenerTest.java:30)
```

**Comment by vibhcool** [comment]
working on this
