### ISSUE TITLE
Google Cloud push to backend fails

### ISSUE THREAD

**Issue by singhpratyush** [loklak/loklak_server#1265]
- Issue type: Bug report

### Short Description
The backend push fails, saying that the request entity is too large.
```java
java.io.IOException: client connection to http://loklak.org/api/push.json fail: 0: Request Entity Too Large
	at org.loklak.http.ClientConnection.init(ClientConnection.java:240) ~[loklak_server-all.jar:?]
	at org.loklak.http.ClientConnection.<init>(ClientConnection.java:155) ~[loklak_server-all.jar:?]
	at org.loklak.api.p2p.PushServlet.push(PushServlet.java:110) [loklak_server-all.jar:?]
	at org.loklak.api.p2p.PushServlet.push(PushServlet.java:123) [loklak_server-all.jar:?]
	at org.loklak.Caretaker.run(Caretaker.java:129) [loklak_server-all.jar:?]
```

There are generally >2k messages to be pushed.

### Environment

 - Software version: Even with `development`
 - Software source: Github Repository

### Steps to reproduce

1. Deploy on Google Cloud with Kubernetes
2. Check for logs via StackDriver - `StackDriver -> Logging`.
3. You can see the failing push attempts.

### Expected behaviour
The messages should get pushed to the backend.

### Actual behaviour
Push to backend fails.

**Comment by singhpratyush** [comment]
@Orbiter @sudheesh001: What can be a good solution for this?

**Comment by vibhcool** [comment]
Is it failing right now?

**Comment by singhpratyush** [comment]
I haven't seen it recently, therefore closing it.
