### ISSUE TITLE
Push to backend fails

### ISSUE THREAD

**Issue by singhpratyush** [loklak/loklak_server#1548]
- Issue type: Bug report

### Short description
The push to backend fails with following exception - 
```
2017-10-07 19:50:15.774:INFO :DAO:CARETAKER: FAILED to push 223 messages to backend http://api.loklak.org
2017-10-07 19:50:15.775:WARN :DAO:CARETAKER: 
java.io.IOException: client connection to http://api.loklak.org/api/push.json fail: 0: Moved Permanently
	at org.loklak.http.ClientConnection.init(ClientConnection.java:240) ~[loklak_server-all.jar:?]
	at org.loklak.http.ClientConnection.<init>(ClientConnection.java:155) ~[loklak_server-all.jar:?]
	at org.loklak.api.p2p.PushServlet.push(PushServlet.java:109) [loklak_server-all.jar:?]
	at org.loklak.api.p2p.PushServlet.push(PushServlet.java:122) [loklak_server-all.jar:?]
	at org.loklak.Caretaker.run(Caretaker.java:117) [loklak_server-all.jar:?]
```

### Environment

 - Operating system: Ubuntu 16.04
 - Software version: Even with `development`
 - Software source: Github Repository

### Steps to reproduce
1. Update local branch.
2. Build project.
3. Start loklak.
4. Check logs

### Expected behaviour
Messages should be pushed to backend.

### Actual behaviour
Pushing to backend fails.

**Comment by singhpratyush** [comment]
Fixed now.
