### ISSUE TITLE
Various Errors under constant load

### ISSUE THREAD

**Issue by smokingwheels** [loklak/loklak_server#16]
![res 24 apr 2015 zoom](https://cloud.githubusercontent.com/assets/11748913/7317165/2bf9d880-eab0-11e4-9b64-8003ae6455f4.JPG)

I wrote a program to time how long a server takes to fill request for an RSS Feed because I was deleting the index folder on all my Peers to get rid of the errors listed below 3 times a day.
My servers have been running for 10 hours with the odd 503 error here or there but not filling the log file with things listed below at a fantastic rate to cause the VM to run out of space.
I will experiment with the DoS settings over the next few days to see what happens.
The pic a graph of loklak.org and how long it takes to complete a RSS feed request.
I ask every 10 seconds.

Some of the errors/WARN I have had over the past week with fixes.

DNS? Fix Destroy Virtual machine and get new IP..
Update Delete index folder.
java.net.UnknownHostException: twitter.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:625)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:933)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at org.loklak.api.ClientHelper.getConnection(ClientHelper.java:51)
	at org.loklak.scraper.TwitterScraper.search(TwitterScraper.java:67)
	at org.loklak.DAO.scrapeTwitter(DAO.java:625)
	at org.loklak.api.server.SearchServlet.doGet(SearchServlet.java:107)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:364)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:309)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:313)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:626)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:546)
	at java.lang.Thread.run(Thread.java:745)

Delete index folder fixes it.

2015-04-20 00:32:42.263:WARN::qtp1246952023-40: [messages][1] null
org.elasticsearch.action.NoShardAvailableActionException: [messages][1] null
	at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction$AsyncSingleAction.perform(TransportShardSingleOperationAction.java:175)
	at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction$AsyncSingleAction.start(TransportShardSingleOperationAction.java:155)
	at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction.doExecute(TransportShardSingleOperationAction.java:89)
	at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction.doExecute(TransportShardSingleOperationAction.java:55)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:75)
	at org.elasticsearch.client.node.NodeClient.execute(NodeClient.java:98)
	at org.elasticsearch.client.support.AbstractClient.get(AbstractClient.java:193)
	at org.elasticsearch.action.get.GetRequestBuilder.doExecute(GetRequestBuilder.java:201)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:91)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:65)
	at org.loklak.DAO.getTweetMap(DAO.java:347)
	at org.loklak.DAO.record(DAO.java:402)
	at org.loklak.DAO.scrapeTwitter(DAO.java:634)
	at org.loklak.api.server.SearchServlet.doGet(SearchServlet.java:107)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:364)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:309)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:313)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:626)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:546)
	at java.lang.Thread.run(Thread.java:745)
2015-04-20 00:32:42.650:INFO::qtp1246952023-40: /

Delete index folder fixes it.

java.lang.IllegalArgumentException: Illegal group reference
	at java.util.regex.Matcher.appendReplacement(Matcher.java:808)
	at java.util.regex.Matcher.replaceFirst(Matcher.java:955)
	at org.loklak.scraper.TwitterScraper$TwitterTweet.<init>(TwitterScraper.java:282)
	at org.loklak.scraper.TwitterScraper.search(TwitterScraper.java:165)
	at org.loklak.scraper.TwitterScraper.search(TwitterScraper.java:70)
	at org.loklak.DAO.scrapeTwitter(DAO.java:625)
	at org.loklak.api.server.SearchServlet.doGet(SearchServlet.java:107)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:364)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:309)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:313)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:626)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:546)
	at java.lang.Thread.run(Thread.java:745)

Delete index folder fixes it.

java.lang.IndexOutOfBoundsException: No group 8
	at java.util.regex.Matcher.start(Matcher.java:374)
	at java.util.regex.Matcher.appendReplacement(Matcher.java:831)
	at java.util.regex.Matcher.replaceFirst(Matcher.java:955)
	at org.loklak.scraper.TwitterScraper$TwitterTweet.<init>(TwitterScraper.java:282)
	at org.loklak.scraper.TwitterScraper.search(TwitterScraper.java:165)
	at org.loklak.scraper.TwitterScraper.search(TwitterScraper.java:70)
	at org.loklak.DAO.scrapeTwitter(DAO.java:625)
	at org.loklak.api.server.SearchServlet.doGet(SearchServlet.java:107)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:364)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:309)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:313)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:626)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:546)
	at java.lang.Thread.run(Thread.java:745)

Connect remote peer to the same peer but another peer.
Eg Fowardends and backends are equal
Loklak still works ok

2015-04-18 11:13:01.683:WARN::qtp16373927-50: 
org.eclipse.jetty.io.EofException
	at org.eclipse.jetty.server.HttpConnection$SendCallback.reset(HttpConnection.java:610)
	at org.eclipse.jetty.server.HttpConnection$SendCallback.access$100(HttpConnection.java:582)
	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:464)
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:766)
	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:804)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:142)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:135)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:373)
	at java.io.OutputStream.write(OutputStream.java:75)
	at org.loklak.api.server.SearchServlet.doGet(SearchServlet.java:203)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:364)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:309)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:313)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:626)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:546)
	at java.lang.Thread.run(Thread.java:745)

After Startup does not happen again. Delete index folder
2015-04-17 03:41:52.533:WARN::qtp403370592-42: Failed to execute phase [query], all shards failed; shardFailures {[Rm52FeIGSlSSmooer2pPYw][messages][0]: SearchParseException[[messages][0]: query[+text:twitter],from[0],size[100]: Parse Failure [Failed to parse source [{"from":0,"size":100,"query":{"bool":{"must":{"match":{"text":{"query":"twitter","type":"boolean"}}}}},"sort":[{"created_at":{"order":"desc"}}]}]]]; nested: SearchParseException[[messages][0]: query[+text:twitter],from[0],size[100]: Parse Failure [No mapping found for [created_at] in order to sort on]]; }{[Rm52FeIGSlSSmooer2pPYw][messages][1]: SearchParseException[[messages][1]: query[+text:twitter],from[0],size[100]: Parse Failure [Failed to parse source [{"from":0,"size":100,"query":{"bool":{"must":{"match":{"text":{"query":"twitter","type":"boolean"}}}}},"sort":[{"created_at":{"order":"desc"}}]}]]]; nested: SearchParseException[[messages][1]: query[+text:twitter],from[0],size[100]: Parse Failure [No mapping found for [created_at] in order to sort on]]; }{[Rm52FeIGSlSSmooer2pPYw][messages][2]: SearchParseException[[messages][2]: query[+text:twitter],from[0],size[100]: Parse Failure [Failed to parse source [{"from":0,"size":100,"query":{"bool":{"must":{"match":{"text":{"query":"twitter","type":"boolean"}}}}},"sort":[{"created_at":{"order":"desc"}}]}]]]; nested: SearchParseException[[messages][2]: query[+text:twitter],from[0],size[100]: Parse Failure [No mapping found for [created_at] in order to sort on]]; }{[Rm52FeIGSlSSmooer2pPYw][messages][3]: SearchParseException[[messages][3]: query[+text:twitter],from[0],size[100]: Parse Failure [Failed to parse source [{"from":0,"size":100,"query":{"bool":{"must":{"match":{"text":{"query":"twitter","type":"boolean"}}}}},"sort":[{"created_at":{"order":"desc"}}]}]]]; nested: SearchParseException[[messages][3]: query[+text:twitter],from[0],size[100]: Parse Failure [No mapping found for [created_at] in order to sort on]]; }{[Rm52FeIGSlSSmooer2pPYw][messages][4]: SearchParseException[[messages][4]: query[+text:twitter],from[0],size[100]: Parse Failure [Failed to parse source [{"from":0,"size":100,"query":{"bool":{"must":{"match":{"text":{"query":"twitter","type":"boolean"}}}}},"sort":[{"created_at":{"order":"desc"}}]}]]]; nested: SearchParseException[[messages][4]: query[+text:twitter],from[0],size[100]: Parse Failure [No mapping found for [created_at] in order to sort on]]; }{[Rm52FeIGSlSSmooer2pPYw][messages][5]: SearchParseException[[messages][5]: query[+text:twitter],from[0],size[100]: Parse Failure [Failed to parse source [{"from":0,"size":100,"query":{"bool":{"must":{"match":{"text":{"query":"twitter","type":"boolean"}}}}},"sort":[{"created_at":{"order":"desc"}}]}]]]; nested: SearchParseException[[messages][5]: query[+text:twitter],from[0],size[100]: Parse Failure [No mapping found for [created_at] in order to sort on]]; }{[Rm52FeIGSlSSmooer2pPYw][messages][6]: SearchParseException[[messages][6]: query[+text:twitter],from[0],size[100]: Parse Failure [Failed to parse source [{"from":0,"size":100,"query":{"bool":{"must":{"match":{"text":{"query":"twitter","type":"boolean"}}}}},"sort":[{"created_at":{"order":"desc"}}]}]]]; nested: SearchParseException[[messages][6]: query[+text:twitter],from[0],size[100]: Parse Failure [No mapping found for [created_at] in order to sort on]]; }{[Rm52FeIGSlSSmooer2pPYw][messages][7]: SearchParseException[[messages][7]: query[+text:twitter],from[0],size[100]: Parse Failure [Failed to parse source [{"from":0,"size":100,"query":{"bool":{"must":{"match":{"text":{"query":"twitter","type":"boolean"}}}}},"sort":[{"created_at":{"order":"desc"}}]}]]]; nested: SearchParseException[[messages][7]: query[+text:twitter],from[0],size[100]: Parse Failure [No mapping found for [created_at] in order to sort on]]; }
org.elasticsearch.action.search.SearchPhaseExecutionException: Failed to execute phase [query], all shards failed; shardFailures {[Rm52FeIGSlSSmooer2pPYw][messages][0]: SearchParseException[[messages][0]: query[+text:twitter],from[0],size[100]: Parse Failure [Failed to parse source [{"from":0,"size":100,"query":{"bool":{"must":{"match":{"text":{"query":"twitter","type":"boolean"}}}}},"sort":[{"created_at":{"order":"desc"}}]}]]]; nested: SearchParseException[[messages][0]: query[+text:twitter],from[0],size[100]: Parse Failure [No mapping found for [created_at] in order to sort on]]; }{[Rm52FeIGSlSSmooer2pPYw][messages][1]: SearchParseException[[messages][1]: query[+text:twitter],from[0],size[100]: Parse Failure [Failed to parse source [{"from":0,"size":100,"query":{"bool":{"must":{"match":{"text":{"query":"twitter","type":"boolean"}}}}},"sort":[{"created_at":{"order":"desc"}}]}]]]; nested: SearchParseException[[messages][1]: query[+text:twitter],from[0],size[100]: Parse Failure [No mapping found for [created_at] in order to sort on]]; }{[Rm52FeIGSlSSmooer2pPYw][messages][2]: SearchParseException[[messages][2]: query[+text:twitter],from[0],size[100]: Parse Failure [Failed to parse source [{"from":0,"size":100,"query":{"bool":{"must":{"match":{"text":{"query":"twitter","type":"boolean"}}}}},"sort":[{"created_at":{"order":"desc"}}]}]]]; nested: SearchParseException[[messages][2]: query[+text:twitter],from[0],size[100]: Parse Failure [No mapping found for [created_at] in order to sort on]]; }{[Rm52FeIGSlSSmooer2pPYw][messages][3]: SearchParseException[[messages][3]: query[+text:twitter],from[0],size[100]: Parse Failure [Failed to parse source [{"from":0,"size":100,"query":{"bool":{"must":{"match":{"text":{"query":"twitter","type":"boolean"}}}}},"sort":[{"created_at":{"order":"desc"}}]}]]]; nested: SearchParseException[[messages][3]: query[+text:twitter],from[0],size[100]: Parse Failure [No mapping found for [created_at] in order to sort on]]; }{[Rm52FeIGSlSSmooer2pPYw][messages][4]: SearchParseException[[messages][4]: query[+text:twitter],from[0],size[100]: Parse Failure [Failed to parse source [{"from":0,"size":100,"query":{"bool":{"must":{"match":{"text":{"query":"twitter","type":"boolean"}}}}},"sort":[{"created_at":{"order":"desc"}}]}]]]; nested: SearchParseException[[messages][4]: query[+text:twitter],from[0],size[100]: Parse Failure [No mapping found for [created_at] in order to sort on]]; }{[Rm52FeIGSlSSmooer2pPYw][messages][5]: SearchParseException[[messages][5]: query[+text:twitter],from[0],size[100]: Parse Failure [Failed to parse source [{"from":0,"size":100,"query":{"bool":{"must":{"match":{"text":{"query":"twitter","type":"boolean"}}}}},"sort":[{"created_at":{"order":"desc"}}]}]]]; nested: SearchParseException[[messages][5]: query[+text:twitter],from[0],size[100]: Parse Failure [No mapping found for [created_at] in order to sort on]]; }{[Rm52FeIGSlSSmooer2pPYw][messages][6]: SearchParseException[[messages][6]: query[+text:twitter],from[0],size[100]: Parse Failure [Failed to parse source [{"from":0,"size":100,"query":{"bool":{"must":{"match":{"text":{"query":"twitter","type":"boolean"}}}}},"sort":[{"created_at":{"order":"desc"}}]}]]]; nested: SearchParseException[[messages][6]: query[+text:twitter],from[0],size[100]: Parse Failure [No mapping found for [created_at] in order to sort on]]; }{[Rm52FeIGSlSSmooer2pPYw][messages][7]: SearchParseException[[messages][7]: query[+text:twitter],from[0],size[100]: Parse Failure [Failed to parse source [{"from":0,"size":100,"query":{"bool":{"must":{"match":{"text":{"query":"twitter","type":"boolean"}}}}},"sort":[{"created_at":{"order":"desc"}}]}]]]; nested: SearchParseException[[messages][7]: query[+text:twitter],from[0],size[100]: Parse Failure [No mapping found for [created_at] in order to sort on]]; }
	at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.onFirstPhaseResult(TransportSearchTypeAction.java:238)
	at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction$1.onFailure(TransportSearchTypeAction.java:184)
	at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:565)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

Working fine.
2015-04-17 14:36:42.500:INFO::qtp403370592-42: /api/search.json?q=ArianaGrande&timezoneOffset=-480&maximumRecords=100&source=twitter&minified=true
java.lang.IndexOutOfBoundsException: No group 7
	at java.util.regex.Matcher.start(Matcher.java:374)
	at java.util.regex.Matcher.appendReplacement(Matcher.java:831)
	at java.util.regex.Matcher.replaceFirst(Matcher.java:955)
	at org.loklak.scraper.TwitterScraper$TwitterTweet.<init>(TwitterScraper.java:282)
	at org.loklak.scraper.TwitterScraper.search(TwitterScraper.java:165)
	at org.loklak.scraper.TwitterScraper.search(TwitterScraper.java:70)
	at org.loklak.DAO.scrapeTwitter(DAO.java:625)
	at org.loklak.api.server.SearchServlet.doGet(SearchServlet.java:107)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:364)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:309)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:313)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:626)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:546)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Orbiter** [comment]
all problems are totally unrelated and addresses bugs which had been reported here already, partly fixed.
