### ISSUE TITLE
Fail TwitterScaperTest

### ISSUE THREAD

**Issue by MarkNomann** [loklak/loklak_server#1632]
An error in TwitterScaperTest:
java.time.format.DateTimeParseException: Text 'Fri Jun 02 09:03:23 CEST 2017' could not be parsed at index 0

	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
	at java.time.LocalDateTime.parse(LocalDateTime.java:492)
	at org.loklak.harvester.TwitterScraperTest.dateFormatChange(TwitterScraperTest.java:198)
	at org.loklak.harvester.TwitterScraperTest.testSimpleSearch(TwitterScraperTest.java:149)

**Comment by MarkNomann** [comment]
The solution that I found:
 ` DateTimeFormatter input_format =
                DateTimeFormatter.ofPattern("EEE MMM dd HH:mm:ss zzz yyyy",new Locale("en"));`

**Comment by callowidealist** [comment]
can i work on it ?

**Comment by MarkNomann** [comment]
Of course, you can test it also.

**Comment by callowidealist** [comment]
Sure @ullf
