### ISSUE TITLE
Wrong format in api/threaddump.txt

### ISSUE THREAD

**Issue by DengYiping** [loklak/loklak_server#171]
```
Thread= Thread-12680  id=14172 RUNNABLE
	at java.net.Socket.connect(Socket.java:579)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.loklak.http.ClientConnection.init(ClientConnection.java:122)
	at org.loklak.http.ClientConnection.&lt;init&gt;(ClientConnection.java:96)
	at org.loklak.http.ClientConnection.download(ClientConnection.java:221)
	at org.loklak.api.client.SearchClient.search(SearchClient.java:44)
	at org.loklak.data.DAO.searchOnOtherPeers(DAO.java:1116)
	at org.loklak.data.DAO.scrapeTwitter(DAO.java:984)
	at org.loklak.api.server.SearchServlet$1.run(SearchServlet.java:113)
```
The code block above is some sample from threaddump api. Since this api returns a txt file instead of html file, ```&lt;``` and ``` &lt;``` should not be here.

**Comment by Orbiter** [comment]
very strange, I do not have these html codes in my threaddumps. There is also no code which could produce this. Please check again and describe your system setup.

**Comment by Orbiter** [comment]
well I have seen this now in my own dumps. I still don't know why this is there...
