### ISSUE TITLE
Frontend pushed too hard

### ISSUE THREAD

**Issue by smokingwheels** [loklak/loklak_server#21]
Search frequency from backend too high causes error frontend peer error
Settings DoS 2500 100
Recommended 3189 by my rough guess program.

2015-05-02 10:59:55.714:INFO::qtp1290568156-42: /api/search.json?q=google&timezoneOffset=-480&maximumRecords=100&source=twitter&minified=true
java.lang.IllegalArgumentException: Illegal group reference
	at java.util.regex.Matcher.appendReplacement(Matcher.java:808)
	at java.util.regex.Matcher.replaceFirst(Matcher.java:955)
	at org.loklak.scraper.TwitterScraper$TwitterTweet.analyse(TwitterScraper.java:307)
	at org.loklak.scraper.TwitterScraper$TwitterTweet.run(TwitterScraper.java:348)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Orbiter** [comment]
I've seen this message myself and provided a fix in https://github.com/loklak/loklak_server/commit/c4e55d0996f788579491143d0cd776769bf4c706
It does not fix the original cause but the outcome probably caused infinite loops which are now prevented
