### ISSUE TITLE
HTTP error 500 on a peer

### ISSUE THREAD

**Issue by smokingwheels** [loklak/loklak_server#248]
I just found this on a peer HTTP error 500
[Error on Search](http://85.25.192.210:9000/api/search.rss?timezoneOffset=-480&q=youtube)

**Comment by smokingwheels** [comment]
Error on Dump and Search
I have a 2 GB Log file It will take me some time to transfer and split.

HTTP ERROR 500

Problem accessing /dump/. Reason:

    Server Error

Caused by:

java.lang.NullPointerException
	at org.loklak.http.RemoteAccess$Post.<init>(RemoteAccess.java:123)
	at org.loklak.http.RemoteAccess.evaluate(RemoteAccess.java:63)
	at org.loklak.api.server.DumpDownloadServlet.doGet(DumpDownloadServlet.java:52)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:364)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:309)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:313)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Powered by Jetty://

**Comment by smokingwheels** [comment]
After long Yellow Status and HTTP 500 Error the log file is flooded with this

2016-02-28 23:24:47.964:WARN::Thread-3: CARETAKER THREAD
java.lang.NullPointerException
	at org.loklak.data.DAO.FullDateHistogram(DAO.java:778)
	at org.loklak.api.client.HelloClient.propagate(HelloClient.java:61)
	at org.loklak.Caretaker.run(Caretaker.java:94)
2016-02-28 23:24:47.964:WARN::Thread-5: DumpImporter THREAD
java.lang.NullPointerException
	at org.loklak.DumpImporter.run(DumpImporter.java:62)
java.lang.NullPointerException
	at org.loklak.data.DAO.countLocal(DAO.java:611)
	at org.loklak.data.DAO.countLocalMessages(DAO.java:590)
	at org.loklak.api.client.HelloClient.propagate(HelloClient.java:56)
	at org.loklak.Caretaker.run(Caretaker.java:94)
2016-02-28 23:24:47.964:WARN::Thread-5: DumpImporter THREAD
java.lang.NullPointerException
	at org.loklak.DumpImporter.run(DumpImporter.java:62)
java.lang.NullPointerException
	at org.loklak.data.DAO.countLocal(DAO.java:611)
	at org.loklak.data.DAO.countLocalUsers(DAO.java:598)
	at org.loklak.api.client.HelloClient.propagate(HelloClient.java:57)
	at org.loklak.Caretaker.run(Caretaker.java:94)
2016-02-28 23:24:47.964:WARN::Thread-5: DumpImporter THREAD
java.lang.NullPointerException
	at org.loklak.DumpImporter.run(DumpImporter.java:62)
2016-02-28 23:24:47.965:WARN::Thread-3: CARETAKER THREAD
java.lang.NullPointerException

**Comment by smokingwheels** [comment]
I am trying my Loklak Server on an Ext2 formated partion because the journal write overhead on the disk was consuming a lot of IO.

**Comment by smokingwheels** [comment]
I click showcase then Home

HTTP ERROR: 500
Problem accessing /index.html. Reason:
 /var/loklak_server/html/index.html (Too many open files)

**Comment by mariobehling** [comment]
As the code basis has changed a lot since the reported error, I am closing this.
