### ISSUE TITLE
Log file floods DumpImporter THREAD java.lang.NullPointerException

### ISSUE THREAD

**Issue by smokingwheels** [loklak/loklak_server#264]
Does it after a upgrade as well, has been running fine for 3-4 days.

2016-02-26 06:49:28.676:WARN::Thread-5: DumpImporter THREAD
java.lang.NullPointerException
	at org.loklak.DumpImporter.run(DumpImporter.java:62)
java.lang.NullPointerException
	at org.loklak.data.DAO.countLocal(DAO.java:611)
	at org.loklak.data.DAO.countLocalUsers(DAO.java:598)
	at org.loklak.api.client.HelloClient.propagate(HelloClient.java:57)
	at org.loklak.Caretaker.run(Caretaker.java:94)

This Maybe the cause.

log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
BindTransportException[Failed to bind to [9300]]; nested: ChannelException[Failed to bind to: localhost/127.0.0.1:9300]; nested: BindException[Address already in use];
	at org.elasticsearch.transport.netty.NettyTransport.bindServerBootstrap(NettyTransport.java:474)
	at org.elasticsearch.transport.netty.NettyTransport.bindServerBootstrap(NettyTransport.java:442)
	at org.elasticsearch.transport.netty.NettyTransport.doStart(NettyTransport.java:319)
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68)
	at org.elasticsearch.transport.TransportService.doStart(TransportService.java:170)
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68)
	at org.elasticsearch.node.Node.start(Node.java:252)
	at org.elasticsearch.node.NodeBuilder.node(NodeBuilder.java:152)
	at org.loklak.data.DAO.init(DAO.java:189)
	at org.loklak.LoklakServer.main(LoklakServer.java:162)
Caused by: org.jboss.netty.channel.ChannelException: Failed to bind to: localhost/127.0.0.1:9300
	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:272)
	at org.elasticsearch.transport.netty.NettyTransport$1.onPortNumber(NettyTransport.java:456)
	at org.elasticsearch.common.transport.PortsRange.iterate(PortsRange.java:58)
	at org.elasticsearch.transport.netty.NettyTransport.bindServerBootstrap(NettyTransport.java:452)
	... 9 more
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.jboss.netty.channel.socket.nio.NioServerBoss$RegisterTask.run(NioServerBoss.java:193)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:391)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:315)
	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Orbiter** [comment]
this is a follow-up problem of the 'does not shutdown' issue because the problem is cause by an already running loklak: "Caused by: java.net.BindException: Address already in use"
Therefore: does not fix. We must fix the other problem.
