### ISSUE TITLE
Loklak failing on scalingo after a short time

### ISSUE THREAD

**Issue by treba123** [loklak/loklak_server#442]
We get this error:
```
2016-05-26 11:06:41.625394068 +0200 CEST [web-1] [stderr] 2016-05-26 09:06:41.336:WARN:oejs.ServletHandler:qtp726374052-107: /cms/topmenu.json
2016-05-26 11:06:41.625513487 +0200 CEST [web-1] [stderr] java.lang.NullPointerException
2016-05-26 11:06:41.625550152 +0200 CEST [web-1] [stderr] 	at org.loklak.server.AbstractAPIHandler.process(AbstractAPIHandler.java:122)
2016-05-26 11:06:41.625607356 +0200 CEST [web-1] [stderr] 	at org.loklak.server.AbstractAPIHandler.doGet(AbstractAPIHandler.java:96)
```

That's the full log:

```
2016-05-26 11:06:27.817194359 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
2016-05-26 11:06:27.817236064 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.server.Server.handle(Server.java:499)
2016-05-26 11:06:27.817279703 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
2016-05-26 11:06:27.817295979 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
2016-05-26 11:06:27.817364714 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
2016-05-26 11:06:27.817379583 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
2016-05-26 11:06:27.817397090 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
2016-05-26 11:06:27.817418229 +0200 CEST [web-1] [stderr] 	at java.lang.Thread.run(Thread.java:745)
2016-05-26 11:06:41.625394068 +0200 CEST [web-1] [stderr] 2016-05-26 09:06:41.336:WARN:oejs.ServletHandler:qtp726374052-107: /cms/topmenu.json
2016-05-26 11:06:41.625513487 +0200 CEST [web-1] [stderr] java.lang.NullPointerException
2016-05-26 11:06:41.625550152 +0200 CEST [web-1] [stderr] 	at org.loklak.server.AbstractAPIHandler.process(AbstractAPIHandler.java:122)
2016-05-26 11:06:41.625607356 +0200 CEST [web-1] [stderr] 	at org.loklak.server.AbstractAPIHandler.doGet(AbstractAPIHandler.java:96)
2016-05-26 11:06:41.625690096 +0200 CEST [web-1] [stderr] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
2016-05-26 11:06:41.625708200 +0200 CEST [web-1] [stderr] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
2016-05-26 11:06:41.625741466 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
2016-05-26 11:06:41.625823629 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
2016-05-26 11:06:41.625881620 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
2016-05-26 11:06:41.625948238 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:365)
2016-05-26 11:06:41.626006917 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
2016-05-26 11:06:41.626114640 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
2016-05-26 11:06:41.626191581 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
2016-05-26 11:06:41.626230864 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
2016-05-26 11:06:41.626306533 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
2016-05-26 11:06:41.626413513 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
2016-05-26 11:06:41.626464794 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
2016-05-26 11:06:41.626508946 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:332)
2016-05-26 11:06:41.626580012 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
2016-05-26 11:06:41.626629073 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.servlets.gzip.GzipHandler.handle(GzipHandler.java:479)
2016-05-26 11:06:41.626680809 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
2016-05-26 11:06:41.626710511 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.server.handler.IPAccessHandler.handle(IPAccessHandler.java:220)
2016-05-26 11:06:41.626736091 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
2016-05-26 11:06:41.626763073 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.server.Server.handle(Server.java:499)
2016-05-26 11:06:41.626835848 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
2016-05-26 11:06:41.626878107 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
2016-05-26 11:06:41.626904291 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
2016-05-26 11:06:41.626938736 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
2016-05-26 11:06:41.626978484 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
2016-05-26 11:06:41.626997389 +0200 CEST [web-1] [stderr] 	at java.lang.Thread.run(Thread.java:745)
2016-05-26 11:06:43.127890948 +0200 CEST [web-1] [stderr] 2016-05-26 09:06:43.039:WARN:oejs.ServletHandler:qtp726374052-106: /cms/topmenu.json
2016-05-26 11:06:43.128044709 +0200 CEST [web-1] [stderr] java.lang.NullPointerException
2016-05-26 11:06:43.128115873 +0200 CEST [web-1] [stderr] 	at org.loklak.server.AbstractAPIHandler.process(AbstractAPIHandler.java:122)
2016-05-26 11:06:43.128154820 +0200 CEST [web-1] [stderr] 	at org.loklak.server.AbstractAPIHandler.doGet(AbstractAPIHandler.java:96)
2016-05-26 11:06:43.128223557 +0200 CEST [web-1] [stderr] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
2016-05-26 11:06:43.128288264 +0200 CEST [web-1] [stderr] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
2016-05-26 11:06:43.128389475 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
2016-05-26 11:06:43.128482108 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
2016-05-26 11:06:43.128528713 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
2016-05-26 11:06:43.128628518 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:365)
2016-05-26 11:06:43.128712564 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
2016-05-26 11:06:43.128750740 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
2016-05-26 11:06:43.128796474 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
2016-05-26 11:06:43.128867703 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
2016-05-26 11:06:43.128890615 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
2016-05-26 11:06:43.128969303 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
2016-05-26 11:06:43.129004628 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
2016-05-26 11:06:43.129024890 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:332)
2016-05-26 11:06:43.129038548 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
2016-05-26 11:06:43.129086710 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.servlets.gzip.GzipHandler.handle(GzipHandler.java:479)
2016-05-26 11:06:43.129111847 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
2016-05-26 11:06:43.129138940 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.server.handler.IPAccessHandler.handle(IPAccessHandler.java:220)
2016-05-26 11:06:43.129167399 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
2016-05-26 11:06:43.129276851 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.server.Server.handle(Server.java:499)
2016-05-26 11:06:43.129351890 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
2016-05-26 11:06:43.129389009 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
2016-05-26 11:06:43.129453621 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
2016-05-26 11:06:43.129517688 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
2016-05-26 11:06:43.129593859 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
2016-05-26 11:06:43.129665422 +0200 CEST [web-1] [stderr] 	at java.lang.Thread.run(Thread.java:745)
2016-05-26 11:07:11.051440223 +0200 CEST [web-1] [stderr] 2016-05-26 09:07:10.841:INFO::Thread-34: trying to push (again) 407 messages to backend, attempt #11/5
2016-05-26 11:08:20.993536448 +0200 CEST [web-1] [stderr] 2016-05-26 09:08:20.941:INFO::Thread-34: trying to push (again) 407 messages to backend, attempt #21/5
2016-05-26 11:09:01.516014945 +0200 CEST [web-1] [stderr] 2016-05-26 09:09:01.465:WARN:oejs.ServletHandler:qtp726374052-198: /cms/topmenu.json
2016-05-26 11:09:01.516152179 +0200 CEST [web-1] [stderr] java.lang.NullPointerException
2016-05-26 11:09:01.516213823 +0200 CEST [web-1] [stderr] 	at org.loklak.server.AbstractAPIHandler.process(AbstractAPIHandler.java:122)
2016-05-26 11:09:01.516269018 +0200 CEST [web-1] [stderr] 	at org.loklak.server.AbstractAPIHandler.doGet(AbstractAPIHandler.java:96)
2016-05-26 11:09:01.516363360 +0200 CEST [web-1] [stderr] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
2016-05-26 11:09:01.516459189 +0200 CEST [web-1] [stderr] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
2016-05-26 11:09:01.516526810 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
2016-05-26 11:09:01.516548900 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
2016-05-26 11:09:01.516565945 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
2016-05-26 11:09:01.516579674 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:365)
2016-05-26 11:09:01.516622549 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
2016-05-26 11:09:01.516655798 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
2016-05-26 11:09:01.516762940 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
2016-05-26 11:09:01.516804280 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
2016-05-26 11:09:01.516823764 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
2016-05-26 11:09:01.516872910 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
2016-05-26 11:09:01.516931075 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
2016-05-26 11:09:01.516978612 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:332)
2016-05-26 11:09:01.517013123 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
2016-05-26 11:09:01.517062622 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.servlets.gzip.GzipHandler.handle(GzipHandler.java:479)
2016-05-26 11:09:01.517110212 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
2016-05-26 11:09:01.517153143 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.server.handler.IPAccessHandler.handle(IPAccessHandler.java:220)
2016-05-26 11:09:01.517181490 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
2016-05-26 11:09:01.517195325 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.server.Server.handle(Server.java:499)
2016-05-26 11:09:01.517212840 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
2016-05-26 11:09:01.517245804 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
2016-05-26 11:09:01.517262055 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
2016-05-26 11:09:01.517305351 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
2016-05-26 11:09:01.517332635 +0200 CEST [web-1] [stderr] 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
2016-05-26 11:09:01.517346898 +0200 CEST [web-1] [stderr] 	at java.lang.Thread.run(Thread.java:745)
2016-05-26 11:09:33.934943076 +0200 CEST [web-1] [stderr] 2016-05-26 09:09:33.798:INFO::Thread-34: trying to push (again) 407 messages to backend, attempt #31/5


```

**Comment by treba123** [comment]
Was a general bug, see https://github.com/loklak/loklak_server/commit/47205a0f1af09a8ab9db2f6b704bfb60d2568fb9
