### ISSUE TITLE
/push/geojson.json Documentation URL's need mandatory screen_name

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_server#517]
The documentation present at http://localhost:9000/api.html#geojsonpush has example request URL as
`http://localhost:9000/api/push/geojson.json?url=mysite.com/mygeojson.json&source_type=IMPORT`
But the `screen_name` is a mandatory field and needs to be a GET parameter.

**Comment by mariobehling** [comment]
Please assign and add milestones to all issues.

**Comment by sudheesh001** [comment]
@Orbiter I think this is an active bug to push geojson `FeatureCollection` objects, I have the following object generated from the following python script
```py
from geojson import Feature, Point, FeatureCollection
my_feature = Feature(geometry=Point((1.6432, -19.123)))
my_other_feature = Feature(geometry=Point((-80.234, -22.532)))
FeatureCollection([my_feature, my_other_feature])
```
Pushing the data into an empty `dict` `{}` resulting in 
```json
{
{
  "features": [
    {
      "geometry": {
        "coordinates": [
          1.6432,
          -19.123
        ],
        "type": "Point"
      },
      "properties": {
        
      },
      "type": "Feature"
    },
    {
      "geometry": {
        "coordinates": [
          -80.234,
          -22.532
        ],
        "type": "Point"
      },
      "properties": {
        
      },
      "type": "Feature"
    }
  ],
  "type": "FeatureCollection"
}
}
```
similar to the one given in the documentation
```json
{
  {
    "type": "FeatureCollection",
    "features" : [
    {
      "type": "Feature",
      "geometry": {"type": "Point", "coordinates": [20.86, 106.68]},
      "properties" :
      {
        "screen_name": "Message 1",
        "user" : {
"screen_name" : "exanonym77s",
"name" : "Example User"
        }
      }
    },
    {
      "type": "Feature",
      "geometry": {"type": "Point", "coordinates": [43.56, 1.46]},
      "properties" :
      {
        "screen_name": "Message 2",
        "user" : {
"screen_name" : "exanonym77s",
"name" : "Example User"
        }
      }
    }
    ]}
}
```
located at the following URL: https://gist.githubusercontent.com/sudheesh001/5b78bfa2252c3ece26388794c6389686/raw/41382402fabbd89458fc2fd27231a70b013a8a98/featureGeo.json

But doing http://localhost:9000/api/push/geojson.json?url=https://gist.githubusercontent.com/sudheesh001/5b78bfa2252c3ece26388794c6389686/raw/2b1df0b08227a6073c14a60def2c1b6e8a816c5a/featureGeo.json&screen_name=sudheesh001

results in the stack trace as
```
HTTP ERROR 500

Problem accessing /api/push/geojson.json. Reason:

    Server Error
Caused by:

org.json.JSONException: JSONObject["text"] not found.
	at org.json.JSONObject.get(JSONObject.java:490)
	at org.loklak.api.iot.GeoJsonPushServlet.doGet(GeoJsonPushServlet.java:149)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1174)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:335)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:418)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1106)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.IPAccessHandler.handle(IPAccessHandler.java:219)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:524)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)
```
