### ISSUE TITLE
NoShardAvailableException when inserting new users to elastic

### ISSUE THREAD

**Issue by zyzo** [loklak/loklak_server#57]
I got `org.elasticsearch.action.NoShardAvailableActionException: [users][7] null` when trying to insert users, not just messages to elastic. 

Reproduce steps : 

1. Uncommenting this [https://github.com/loklak/loklak_server/blob/new-push-api/src/org/loklak/api/server/GeoJsonPushServlet.java#L138](line)
2. Recompile & rerun loklak
3. Execute this command (make sure the messages don't exist yet in db) : 
```sh
curl -i -F callback=p \
        -F url=http://cmap-fossasia-api.herokuapp.com/ffGeoJsonp.php \
        -F map_type=shortname:screen_name,shortname:user.screen_name,name:user.name,url:link \
        http://localhost:9000/api/geojsonpush.json
```

What is strange is that the exception is not raised from the start, but rather after several successful insertions. Here's a snapshot of inserted users : 
![](http://img11.hostingpics.net/pics/334586Screenshotfrom20150627094221.png)

Stack trace : 
```
2015-06-27 11:04:40.380:WARN:oejs.ServletHandler:qtp1740472127-59: /api/geojsonpush.json
org.elasticsearch.action.NoShardAvailableActionException: [users][7] null
	at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction$AsyncSingleAction.perform(TransportShardSingleOperationAction.java:175)
	at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction$AsyncSingleAction.start(TransportShardSingleOperationAction.java:155)
	at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction.doExecute(TransportShardSingleOperationAction.java:89)
	at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction.doExecute(TransportShardSingleOperationAction.java:55)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:75)
	at org.elasticsearch.client.node.NodeClient.execute(NodeClient.java:98)
	at org.elasticsearch.client.support.AbstractClient.get(AbstractClient.java:193)
	at org.elasticsearch.action.get.GetRequestBuilder.doExecute(GetRequestBuilder.java:201)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:91)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:65)
	at org.loklak.data.AbstractIndexFactory.exists(AbstractIndexFactory.java:60)
	at org.loklak.data.DAO.writeMessage(DAO.java:501)
	at org.loklak.api.server.GeoJsonPushServlet.doPost(GeoJsonPushServlet.java:139)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:300)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:309)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:313)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:626)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:546)
	at java.lang.Thread.run(Thread.java:745)
```

PR #56

**Comment by zyzo** [comment]
Error due to an unassigned shard. 
This command which reassigned [users][7] to `Bizarnage` node solved the bug : 
```sh`
curl -XPOST 'localhost:9200/_cluster/reroute' -d '{
        "commands" : [ {
              "allocate" : {
                  "index" : "users",
                  "shard" : "7",
                  "node" : "Bizarnage",
                  "allow_primary" : true
              }
            }
        ]
    }'
```

Fix found here https://t37.net/how-to-fix-your-elasticsearch-cluster-stuck-in-initializing-shards-mode.html
