### ISSUE TITLE
Extract information from Reddit

### ISSUE THREAD

**Issue by jig08** [loklak/loklak_server#570]
[Reddit](https://www.reddit.com/) has become quite popular these days. It is an entertainment, social news networking service, and news website. 

Without needing any `oauth/access_tokens` we can extract information from the `HTML Results Page` of [https://www.reddit.com/?q="search-term"](https://www.reddit.com).

@Orbiter @mariobehling Suggestion and Feedback appreciated :grinning:

**Comment by Orbiter** [comment]
reddit has rss for the main page: https://www.reddit.com/.rss
and as well for the search result: https://www.reddit.com/search.rss?q=loklak
don't scrape it, use the rss

**Comment by jig08** [comment]
Oh yes, @Orbiter Gotcha.

**Comment by jig08** [comment]
**TODO:** Look into why [http://loklak.org/api/rssreader.json?url=https://www.reddit.com/.rss](http://loklak.org/api/rssreader.json?url=https://www.reddit.com/.rss) gives a `null pointer exception`

```
HTTP ERROR 500

Problem accessing /api/rssreader.json. Reason:

    Server Error
Caused by:

java.lang.NullPointerException
	at org.loklak.api.search.RSSReader.doGet(RSSReader.java:89)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1174)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:335)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:418)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1106)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.IPAccessHandler.handle(IPAccessHandler.java:219)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:524)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jig08** [comment]
Resolved by adding `NULL` checks & `ClientConnection` via commit https://github.com/loklak/loklak_server/commit/8a589ba2995b4bb176856f46d92505de57d4d1eb
