### ISSUE TITLE
loklak does not start because of missing library

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_server#577]
on loklak.org, loklak fails to start!

with https://github.com/loklak/loklak_server/commit/10993ac9f5b5d76b7f4ce8aca398b62cf5d5550a we can see now this error
```
loklak@host000:/tmp$ tail -1000 loklak_201606130751.log 
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/log4j/or/RendererMap
	at org.apache.log4j.Hierarchy.<init>(Hierarchy.java:97)
	at org.apache.log4j.LogManager.<clinit>(LogManager.java:82)
	at org.apache.log4j.Logger.getLogger(Logger.java:104)
	at org.elasticsearch.common.logging.log4j.Log4jESLoggerFactory.newInstance(Log4jESLoggerFactory.java:38)
	at org.elasticsearch.common.logging.ESLoggerFactory.newInstance(ESLoggerFactory.java:82)
	at org.elasticsearch.common.logging.ESLoggerFactory.getLogger(ESLoggerFactory.java:66)
	at org.elasticsearch.common.logging.Loggers.getLogger(Loggers.java:121)
	at org.elasticsearch.common.settings.Settings.<clinit>(Settings.java:63)
	at org.loklak.data.ElasticsearchClient.<init>(ElasticsearchClient.java:110)
	at org.loklak.data.DAO.init(DAO.java:203)
	at org.loklak.LoklakServer.main(LoklakServer.java:215)
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.or.RendererMap
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 11 more
```
The cause is this pull request here:
https://github.com/loklak/loklak_server/commit/498c5f5bcdd949c02ecb0efdc23082866a98acb3

We need either that library back again or another solution.

**Comment by treba123** [comment]
Please clear your installation directory and rebuild. That error should occur then.

**Comment by treba123** [comment]
By the way, the travis build system is now able to check if loklak starts up fine. So all new push requests are checked before they are merged.
So if the startup fails, the problem should usually be searched for on the user system.

**Comment by Orbiter** [comment]
ok, lets include the 'clean' in bin/upgrade.sh

**Comment by treba123** [comment]
done, https://github.com/loklak/loklak_server/pull/584
