### ISSUE TITLE
Server Crash not responding on http.

### ISSUE THREAD

**Issue by smokingwheels** [loklak/loklak_server#652]
Update interval had an extra "000" added.

2016-07-04 01:59:47.930:WARN :org.eclipse.jetty.server.AbstractConnector:qtp1239593925-104-acceptor-0@31a8873c-httpd:9001@3f6f6f79{HTTP/1.1,[http/1.1]}{0.0.0.0:9001}: 
java.nio.channels.ClosedSelectorException
	at sun.nio.ch.SelectorImpl.keys(SelectorImpl.java:68) ~[?:1.8.0_91]
	at org.eclipse.jetty.io.ManagedSelector.size(ManagedSelector.java:104) ~[jetty-io-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.io.SelectorManager.chooseSelector(SelectorManager.java:190) ~[jetty-io-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.io.SelectorManager.accept(SelectorManager.java:232) ~[jetty-io-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.io.SelectorManager.accept(SelectorManager.java:217) ~[jetty-io-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.ServerConnector.accepted(ServerConnector.java:383) ~[jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:374) ~[jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:593) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [jetty-util-9.3.9.v20160517.jar:9.3.9.v20160517]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [jetty-util-9.3.9.v20160517.jar:9.3.9.v20160517]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
2016-07-04 02:00:19.774:INFO :org.loklak.data.DAO:Thread-16221: /api/search.rss scraping with query: @ausvotes
2016-07-04 02:00:28.130:INFO :org.loklak.data.DAO:Thread-16223: searchOnOtherPeers: no IO to scraping target: GC overhead limit exceeded
2016-07-04 02:00:33.178:INFO :org.loklak.data.DAO:qtp1239593925-14674: /api/search.rss?q=%40ausvotes -> 0 records returned, 0 new
2016-07-04 02:01:36.214:WARN :org.eclipse.jetty.util.thread.QueuedThreadPool$2:qtp1239593925-104: 
java.lang.OutOfMemoryError: GC overhead limit exceeded
2016-07-04 02:01:37.422:WARN :org.eclipse.jetty.util.thread.QueuedThreadPool$2:qtp1239593925-104: Unexpected thread death: org.eclipse.jetty.util.thread.QueuedThreadPool$2@555947f8 in qtp1239593925{STARTED,8<=8<=500,i=6,q=0}

**Comment by treba123** [comment]
Hm, the `GC overhead limit exceeded` sounds like insufficient ram or a memory leak. How long did the instance run already?

**Comment by smokingwheels** [comment]
Ok I only have 4 GB of memory running the default.
I run Yacy, Loklak and Thinlinc Server on a core 2 quad.
My memory usage of swap runs at 1-2 GB on a SSD. 

@treba123 If you run a custom config do you have to list all the properties in it?

**Comment by treba123** [comment]
I don't have any custom settings related to that atm, but the two things that come to my mind are:

- putting `Xmx=1000m` or bigger into your `customized_config.properties` (if your system is not already under pressure)
- export ES_HEAP_SIZE=(some size smaller than your Xmx, maybe 800m)

If I get it right now, the above error occurs if the GC is not able to clear atleast 2% of the memory and basicly runs all the time.
It would be really interesting if it was just elasticsearch which grew to big or if there's something in the rest of the loklak code that does not get cleaned up.

**Comment by smokingwheels** [comment]
top command in bash both running.
 3497 root      30  10 10.388g 1.130g 117372 S   0.7 29.3  15:00.69 java
Ended loklak
 3497 root      30  10 10.388g 1.127g 115008 S  24.6 29.2  15:04.44 java
Loklak running again its process
18209 root      20   0 4939704 726788  42488 S  97.9 18.0   1:00.51 java
Will monitor it when loklak crashes again.
I can't find anything yet that works to monitor a PID.

**Comment by smokingwheels** [comment]
top command in bash both running.
 3497 root      30  10 10.388g 1.130g 117372 S   0.7 29.3  15:00.69 java
Ended loklak
 3497 root      30  10 10.388g 1.127g 115008 S  24.6 29.2  15:04.44 java
Loklak running again its process
18209 root      20   0 4939704 726788  42488 S  97.9 18.0   1:00.51 java
Will monitor it when loklak crashes again.
I can't find anything yet that works to monitor a PID.

I have created another Swap image
cd /usr
touch swap2.img
chmod 600 swap2.img
dd if=/dev/zero of=/usr/swap2.img bs=8196k count=1000
mkswap /usr/swap2.img
swapon /usr/swap2.img
echo "/usr/swap2.img none swap sw 0 0" >> /etc/fstab

I will see what happens now have 16 GB of Swap.

**Comment by smokingwheels** [comment]
Both Loklak and Yacy have been up for 1 Day 19 hours with 16 GB of swap on the one PC.
 You can log it sort of with top -p 19032 > mem.txt

19032 root      39  19 10.480g 1.038g  98300 S   7.3 26.9  90:52.91 java

**Comment by treba123** [comment]
@smokingwheels afaik, both loklak and yacy should be limited by their corresponding Xmx values. So even together they shouldn't have more than 2gb of memory allocated.
If your mashine has 8gb of ram, I doubt the swap file will be used alot.

About the profiling: I use visualvm on my mashine, a pretty nice tool. It's also possible to use it remotely with a headless server, see [here](http://www.codefactorycr.com/java-visualvm-to-profile-a-remote-server.html).

**Comment by treba123** [comment]
Closing for the time being. Maybe we should consider increasing the default xmx value.
