### ISSUE TITLE
Elasticsearch crash or something

### ISSUE THREAD

**Issue by smokingwheels** [loklak/loklak_server#664]
After crashing Loklak refused to start just kept filling logs and churning them thru.
Low memory PC running Yacy and ThinLinc Servers.
Automatic Update interval an extra "000".
Maybe related to Issue #652 .

Contents. 7Zip [Here](http://sw.remote.mx/Download/temp.7z)

2016-07-06 23:26:33.546:WARN :org.elasticsearch.indices.cluster.IndicesClusterStateService:elasticsearch[Nefarius][generic][T#1]: [Nefarius] [[messages_week][5]] marking and sending shard failed due to [failed recovery]
org.elasticsearch.index.shard.IndexShardRecoveryException: failed recovery
	at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:179) [elasticsearch-2.3.2.jar:2.3.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.IllegalStateException: Checkpoint file translog-177.ckp already exists but has corrupted content expected: Checkpoint{offset=1343213, numOps=1265, translogFileGeneration= 177} but got: Checkpoint{offset=1342383, numOps=1264, translogFileGeneration= 177}
	at org.elasticsearch.index.translog.Translog.recoverFromFiles(Translog.java:339) ~[elasticsearch-2.3.2.jar:2.3.2]
	at org.elasticsearch.index.translog.Translog.<init>(Translog.java:179) ~[elasticsearch-2.3.2.jar:2.3.2]
	at org.elasticsearch.index.engine.InternalEngine.openTranslog(InternalEngine.java:208) ~[elasticsearch-2.3.2.jar:2.3.2]
	at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:151) ~[elasticsearch-2.3.2.jar:2.3.2]
	at org.elasticsearch.index.engine.InternalEngineFactory.newReadWriteEngine(InternalEngineFactory.java:25) ~[elasticsearch-2.3.2.jar:2.3.2]
	at org.elasticsearch.index.shard.IndexShard.newEngine(IndexShard.java:1515) ~[elasticsearch-2.3.2.jar:2.3.2]
	at org.elasticsearch.index.shard.IndexShard.createNewEngine(IndexShard.java:1499) ~[elasticsearch-2.3.2.jar:2.3.2]
	at org.elasticsearch.index.shard.IndexShard.internalPerformTranslogRecovery(IndexShard.java:972) ~[elasticsearch-2.3.2.jar:2.3.2]
	at org.elasticsearch.index.shard.IndexShard.performTranslogRecovery(IndexShard.java:944) ~[elasticsearch-2.3.2.jar:2.3.2]
	at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:241) ~[elasticsearch-2.3.2.jar:2.3.2]
	at org.elasticsearch.index.shard.StoreRecoveryService.access$100(StoreRecoveryService.java:56) ~[elasticsearch-2.3.2.jar:2.3.2]
	at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:129) ~[elasticsearch-2.3.2.jar:2.3.2]
	... 3 more
2016-07-06 23:26:33.547:WARN :org.elasticsearch.cluster.action.shard.ShardStateAction:elasticsearch[Nefarius][generic][T#1]: [Nefarius] [messages_week][5] received shard failed for target shard [[messages_week][5], node[XqS7dS2CQTiAiosEIs5iUA], [P], v[13], s[INITIALIZING], a[id=nunRTKg7QviXqyqhxAHIHQ], unassigned_info[[reason=ALLOCATION_FAILED], at[2016-07-06T15:26:33.537Z], details[failed recovery, failure IndexShardRecoveryException[failed recovery]; nested: IllegalStateException[Checkpoint file translog-177.ckp already exists but has corrupted content expected: Checkpoint{offset=1343213, numOps=1265, translogFileGeneration= 177} but got: Checkpoint{offset=1342383, numOps=1264, translogFileGeneration= 177}]; ]]], indexUUID [8GqX4IlZR9On6qmTN28ueA], message [failed recovery], failure [IndexShardRecoveryException[failed recovery]; nested: IllegalStateException[Checkpoint file translog-177.ckp already exists but has corrupted content expected: Checkpoint{offset=1343213, numOps=1265, translogFileGeneration= 177} but got: Checkpoint{offset=1342383, numOps=1264, translogFileGeneration= 177}]; ]
org.elasticsearch.index.shard.IndexShardRecoveryException: failed recovery
	at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:179) [elasticsearch-2.3.2.jar:2.3.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.IllegalStateException: Checkpoint file translog-177.ckp already exists but has corrupted content expected: Checkpoint{offset=1343213, numOps=1265, translogFileGeneration= 177} but got: Checkpoint{offset=1342383, numOps=1264, translogFileGeneration= 177}
	at org.elasticsearch.index.translog.Translog.recoverFromFiles(Translog.java:339) ~[elasticsearch-2.3.2.jar:2.3.2]
	at org.elasticsearch.index.translog.Translog.<init>(Translog.java:179) ~[elasticsearch-2.3.2.jar:2.3.2]
	at org.elasticsearch.index.engine.InternalEngine.openTranslog(InternalEngine.java:208) ~[elasticsearch-2.3.2.jar:2.3.2]
	at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:151) ~[elasticsearch-2.3.2.jar:2.3.2]
	at org.elasticsearch.index.engine.InternalEngineFactory.newReadWriteEngine(InternalEngineFactory.java:25) ~[elasticsearch-2.3.2.jar:2.3.2]
	at org.elasticsearch.index.shard.IndexShard.newEngine(IndexShard.java:1515) ~[elasticsearch-2.3.2.jar:2.3.2]
	at org.elasticsearch.index.shard.IndexShard.createNewEngine(IndexShard.java:1499) ~[elasticsearch-2.3.2.jar:2.3.2]
	at org.elasticsearch.index.shard.IndexShard.internalPerformTranslogRecovery(IndexShard.java:972) ~[elasticsearch-2.3.2.jar:2.3.2]
	at org.elasticsearch.index.shard.IndexShard.performTranslogRecovery(IndexShard.java:944) ~[elasticsearch-2.3.2.jar:2.3.2]
	at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:241) ~[elasticsearch-2.3.2.jar:2.3.2]
	at org.elasticsearch.index.shard.StoreRecoveryService.access$100(StoreRecoveryService.java:56) ~[elasticsearch-2.3.2.jar:2.3.2]
	at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:129) ~[elasticsearch-2.3.2.jar:2.3.2]
	... 3 more
2016-07-06 23:26:33.556:WARN :org.elasticsearch.indices.cluster.IndicesClusterStateService:elasticsearch[Nefarius][generic][T#1]: [Nefarius] [[messages_week][5]] marking and sending shard failed due to [failed recovery]
org.elasticsearch.index.shard.IndexShardRecoveryException: failed recovery
	at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:179) [elasticsearch-2.3.2.jar:2.3.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.IllegalStateException: Checkpoint file translog-177.ckp already exists but has corrupted content expected: Checkpoint{offset=1343213, numOps=1265, translogFileGeneration= 177} but got: Checkpoint{offset=1342383, numOps=1264, translogFileGeneration= 177}
	at org.elasticsearch.index.translog.Translog.recoverFromFiles(Translog.java:339) ~[elasticsearch-2.3.2.jar:2.3.2]
	at org.elasticsearch.index.translog.Translog.<init>(Translog.java:179) ~[elasticsearch-2.3.2.jar:2.3.2]
	at org.elasticsearch.index.engine.InternalEngine.openTranslog(InternalEngine.java:208) ~[elasticsearch-2.3.2.jar:2.3.2]
	at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:151) ~[elasticsearch-2.3.2.jar:2.3.2]
	at org.elasticsearch.index.engine.InternalEngineFactory.newReadWriteEngine(InternalEngineFactory.java:25) ~[elasticsearch-2.3.2.jar:2.3.2]
	at org.elasticsearch.index.shard.IndexShard.newEngine(IndexShard.java:1515) ~[elasticsearch-2.3.2.jar:2.3.2]
	at org.elasticsearch.index.shard.IndexShard.createNewEngine(IndexShard.java:1499) ~[elasticsearch-2.3.2.jar:2.3.2]
	at org.elasticsearch.index.shard.IndexShard.internalPerformTranslogRecovery(IndexShard.java:972) ~[elasticsearch-2.3.2.jar:2.3.2]
	at org.elasticsearch.index.shard.IndexShard.performTranslogRecovery(IndexShard.java:944) ~[elasticsearch-2.3.2.jar:2.3.2]
	at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:241) ~[elasticsearch-2.3.2.jar:2.3.2]
	at org.elasticsearch.index.shard.StoreRecoveryService.access$100(StoreRecoveryService.java:56) ~[elasticsearch-2.3.2.jar:2.3.2]
	at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:129) ~[elasticsearch-2.3.2.jar:2.3.2]
	... 3 more

**Comment by treba123** [comment]
For a first impression, it looks similar to a bug @daminisatya had yesterday ([here](https://gitter.im/loklak/loklak?at=577cdf89fccf53c605c4bad9)).
The solution was to remove the broken index file.
If you don't mind, remove data/index or just the mentioned file translog-177.ckp and try again.

**Comment by daminisatya** [comment]
@treba123 @smokingwheels Exactly, it worked after deleting the nodes.

**Comment by smokingwheels** [comment]
I will take you word for it.. 
Thanks
