### ISSUE TITLE
NullPointerException when searching loklak

### ISSUE THREAD

**Issue by zyzo** [loklak/loklak_server#90]
Context : searching for things via /api/search.json
Stack trace
```
Exception in thread "Thread-28" java.lang.NullPointerException
	at org.loklak.data.Classifier$Context.learnPhrase(Classifier.java:95)
	at org.loklak.data.Classifier.learnPhrase(Classifier.java:116)
	at org.loklak.data.DAO.writeMessage(DAO.java:426)
	at org.loklak.data.DAO.searchOnOtherPeers(DAO.java:887)
	at org.loklak.data.DAO.searchBackend(DAO.java:875)
	at org.loklak.api.server.SearchServlet$2.run(SearchServlet.java:110)
```

It seems like `categories` is not initialized properly and contain some entry with value=null.

**Comment by zyzo** [comment]
Caused by #108 which is fixed.
