### ISSUE TITLE
Failed pushing 100 messages to backend

### ISSUE THREAD

**Issue by smokingwheels** [loklak/loklak_server#91]
Had the error on a couple of servers. Total of 4 running in overload mode scraping. 
I updated them 30-7-15
I will try changing or adding my backend if needed.
Total of 4 running in overload mode scraping. 
I changed my config so that I run 1 backend and 3 fronts and use my backend to push to loklak.org.
Its some sort of timing problem I think.
Also the data on loklak.org was not increasing with this condition.

Lots of these messages and the average CPU load on my peer sits around 7, was 10

java.io.IOException: client connection to http://loklak.org/api/push.json fail: 500: Server Error
	at org.loklak.api.client.ClientConnection.<init>(ClientConnection.java:124)
	at org.loklak.api.client.PushClient.push(PushClient.java:54)
	at org.loklak.Caretaker.run(Caretaker.java:82)
2015-07-30 04:50:38.909:INFO::Thread-17: failed pushing 100 messages to backend

**Comment by smokingwheels** [comment]
Running my own Backend haven't had a problem but my timing values are a lot lower than 100 1000.
