### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by smokingwheels** [loklak/loklak_server#92]
Interface not responding Debian 7 64 bit Average load ~7 to 9 for 6 hours.
Swap file stable and some room left.
Java process still in memory on consuming CPU time. 
System 768 meg ram and SSD.
Others are working fine similar overload conditions for same period.

/api/search.rss is line above WARN

2015-07-30 08:18:38.137:WARN::qtp743087655-7655: 
java.util.ConcurrentModificationException
	at java.util.TreeMap$DescendingMapIterator.makePrev(TreeMap.java:385)
	at java.util.TreeMap$UnboundedDescendingEntryIterator.next(TreeMap.java:452)
	at java.util.TreeMap$UnboundedDescendingEntryIterator.next(TreeMap.java:437)
	at java.util.AbstractMap$2$1.next(AbstractMap.java:385)
	at org.loklak.api.server.SearchServlet.doGet(SearchServlet.java:214)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:364)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:309)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:313)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:626)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:546)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Orbiter** [comment]
fixed with https://github.com/loklak/loklak_server/commit/05f41fe615be101b56c8781089ecd295f75e936e

**Comment by smokingwheels** [comment]
Cheers @Orbiter
