### ISSUE TITLE
Failed pushing 100 messages to backend client connection error

### ISSUE THREAD

**Issue by smokingwheels** [loklak/loklak_server#98]
Error happens with 3 of 4 front peers are connected pushing messages to Backend.
This error does not show on my other lan peer. I only have ADSL2+.

I also had this problem when I was running 4 Independent peers pushing back to loklak.org using the wget command with no sleep x function.

2015-07-31 20:42:15.097:INFO::qtp1605401271-6790: /api/search.json?q=AvrilLavigne&timezoneOffset=0&maximumRecords=100&source=twitter&minified=true -> 20 records returned, 20 new
java.io.IOException: client connection to http://204.261.287.178:9000/api/push.json fail: 500: Server Error
	at org.loklak.api.client.ClientConnection.<init>(ClientConnection.java:124)
	at org.loklak.api.client.PushClient.push(PushClient.java:54)
	at org.loklak.Caretaker.run(Caretaker.java:82)
2015-07-31 20:42:15.357:INFO::Thread-17: failed pushing 100 messages to backend

**Comment by smokingwheels** [comment]
Not getting this error any more I use VM's some times to do harvesting with decent bandwidth
